name: Docker Build Environment Image CI

on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - '.github/workflows/docker-build-env.yml'
      - 'support/docker/Dockerfile-build-env_**'

jobs:
  docker:
    name: ${{ matrix.platform}}_netpanzer-build-env_${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        tag: [jammy, focal]
        platform: ['linux/amd64','linux/arm64']
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}
          password: ${{ secrets.UNCLE_ANDY_DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: ${{ contains(matrix.platform, 'amd64') }}
        run: |
          export ARCH="x86_64"
          echo "ARCH=${ARCH}" >> $GITHUB_ENV

      - if: ${{ contains(matrix.platform, 'arm64') }}
        run: |
          export ARCH="aarch64"
          echo "ARCH=${ARCH}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./support/docker/Dockerfile-build-env_${{ matrix.tag }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}/netpanzer-build-env:${{ matrix.tag }}
          cache-from: type=registry,ref=${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}/netpanzer-build-env:buildcache
          cache-to: type=registry,ref=${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}/netpanzer-build-env:buildcache,mode=max
